const errors = {
  networkError: 'Hubo un error de conexi√≥n, intente de nuevo.',
  generalError: 'Ha ocurrido un error, intente nuevamente.',
};

export default errors;
